# Generated by Django 5.1.3 on 2024-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
